version: '3.8'

services:
  # FastAPI
  app:
    build: .
    container_name: fastapi_app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      # MySQL
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=rsrs

      # DynamoDB Local
      - DYNAMODB_ENDPOINT_URL=http://dynamodb:8000
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_REGION=ap-northeast-2
    depends_on:
      - db
      - dynamodb

  # MySQL
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=rsrs
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # DynamoDB Local
  dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb_local
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data" # 공유 DB 모드로 실행
    working_dir: /home/dynamodblocal
    ports:
      - "8001:8000"
    volumes:
      - dynamodb_data:/home/dynamodblocal/data

volumes:
  db_data:
  dynamodb_data:
