version: '3.8'

services:
  # FastAPI
  app:
    image: python:3.9-slim
    container_name: fastapi_app
    working_dir: /app
    command: >
      bash -lc "pip install --no-cache-dir -r requirements.txt &&
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
      - ./data:/app/data
    ports:
      - "8000:8000"
    environment:
      # MySQL
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=rsrs

      # MongoDB
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_USER=root
      - MONGO_PASSWORD=capstone02
      - MONGO_AUTH_SOURCE=admin
      - MONGO_DB=arxiv
      - MONGO_COLLECTION=arxiv_papers

      # Kaggle
      - KAGGLE_CONFIG_DIR=/app/data
    depends_on:
      - db
      - mongo

  # MySQL
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=rsrs
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # MongoDB
  mongo:
    image: mongo:6
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=capstone02
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  db_data:
  mongo_data:
